name: my_app
description: A new Flutter project

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/image.png
    - assets/music.mp3
    
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
